BREED_DESCRIPTIONS = {
    "Chihuahua": "A small, lively, and alert dog breed known for its loyalty and big personality. Great for apartment living.",
    "Shih-Tzu": "A charming toy breed with a luxurious coat. Friendly and great for companionship.",
    "Toy Terrier": "A tiny but energetic breed, known for its intelligence and playful nature.",
    "Italian Greyhound": "A sleek, affectionate breed with a strong desire to be close to its owner. Ideal for warm climates.",
    "American Staffordshire Terrier": "Strong and confident, yet affectionate. Known for loyalty and being good with families.",
    "Bedlington Terrier": "A unique breed with a lamb-like appearance, friendly, and great for active owners.",
    "Border Terrier": "A sturdy and good-natured breed, great for families and active individuals.",
    "Standard Schnauzer": "A highly intelligent and protective breed. Ideal for working and guarding purposes.",
    "Tibetan Terrier": "A medium-sized dog with a friendly and affectionate nature. Originally bred for herding in Tibet.",
    "Silky Terrier": "Small and elegant with a beautiful silky coat. Active and affectionate.",
    "Flat-Coated Retriever": "A friendly and intelligent retriever, known for its boundless energy and love for water.",
    "Curly-Coated Retriever": "A highly trainable retriever with a dense, curly coat. Excellent for outdoor activities.",
    "Golden Retriever": "Friendly, intelligent, and highly trainable. One of the best family dogs.",
    "Labrador Retriever": "Outgoing, affectionate, and highly trainable. Great for families and active individuals.",
    "Chesapeake Bay Retriever": "A strong and versatile retriever breed, great for water retrieving and hunting.",
    "Collie": "Loyal and intelligent herding dog, known for its gentle nature and love for families.",
    "Rottweiler": "Confident, fearless,ferocious and protective. A strong guard dog with a loving side.",
    "German Shepherd": "A highly intelligent and trainable working dog. Excellent for security and companionship.",
    "Doberman": "Athletic and loyal, known for its intelligence and protective instincts.",
    "Boxer": "Playful and affectionate, great with families and children. Highly energetic.",
    "Bull Mastiff": "A powerful guard dog, protective yet affectionate with its family.",
    "Tibetan Mastiff": "A massive and independent dog, originally bred to guard livestock in the Himalayas.",
    "French Bulldog": "A small, muscular breed with a charming and playful personality. Great for apartments.",
    "Great Dane": "A gentle giant with a calm and affectionate nature. Good with families.",
    "Saint Bernard": "A large and loving breed, originally bred for mountain rescues. Gentle and protective.",
    "Siberian Husky": "A strong, independent breed with high energy levels. Known for endurance and working in cold climates.",
    "Pug": "A small and charming breed with a fun-loving personality. Loves human companionship.",
    "Pomeranian": "A tiny and fluffy breed with a big personality. Lively and highly trainable.",
    "Toy Poodle": "A small and intelligent breed, easy to train and great for families.",
    "Miniature Poodle": "A highly intelligent breed, great for allergy sufferers and highly trainable.",
    "Standard Poodle": "An intelligent and active breed. Known for its elegance and hypoallergenic coat."
}
